setting:
  # 插件前缀
  prefix: "§l§bWasteAC §f>> "
  # WasteAC验证服务器端口
  port: 1922
  # 是否检测op
  check_admin: false
  # 自动删除N天前的日志 小于0为永不删除
  auto_del_logs: 3
  # 玩家数据路径
  # 变量: [WasteAC] WasteAC插件根目录
  # 例如: [WasteAC]/playerData.yml
  playerData: "[WasteAC]/playerData.yml"
  # 被排除的世界不检测
  excluded_worlds:
    - "lobby"
  # 调试模式(训练模型需要开启)
  # 如果test_mode开启了那么debug会广播给所有人反之则广播给自己
  debug: false
  # 每N秒减少1Kvl (所有作弊项的Kvl)
  reduce_kvl: 180
  # 每N秒减少1Vl (所有作弊项的Vl)
  reduce_vl: 30
  # 每N秒减少1Flag (所有作弊项的Flag)
  reduce_flag: 10
  # 处理延迟卡顿
  process_lag:
    enable: true
    # 等待 N tick后恢复
    restore_tick: 40
    # 低TPS保护
    min_tps: 18.0
    # 高PING保护
    high_ping: 100
  # CmdWave延迟秒数
  CmdWave: 6
  # 此功能用于WasteAC测试服
  test_mode: # 开启后新增give指令功能
    enable: false
    # 玩家进入(除op)
    player_join: true
    # 世界名称
    level: test
    # 玩家在这个范围内会开启FFA
    ffa_range: #xz
      start: 0:0
      end: 0:0
    # 世界管理员
    world_admin:
      - "ggk1030"
  # kvl|cmd=命令|是否清除kvl值|是否广播|是否使用CmdWave|addBvl=int
  # 描述:
  #   vl等于N时执行对应操作
  #   CmdWave能够延迟N秒执行操作
  #   指令由控制台执行
  #   支持变量:
  #   %player% - 玩家名称
  #   %type% - 作弊类型
  #   可以不填写
  kvl_event:
    - "3:cmd=wac ban %player% %bannedMes%:true:true:true:addBvl=0"
  # bvl|cmd=命令|是否清除bvl值|是否广播|是否使用CmdWave
  # 描述见kvl_event (一样)
  bvl_event: [ ]
  # Flag警告
  warning: #填空则代表不发送
    #默认变量:
    # %player% - 作弊玩家
    # %type% - 作弊类型
    # title格式 title:subtitle
    title: ""
    message: ""
    actionbar: ""
  # 默认变量
  # %player% - 作弊玩家
  # %type% - 作弊类型
  kick_message: |-
    §r§r
                §l§c>> KICK MESSAGE <<
        §i游戏数据异常,你的连接已从服务器断开
    §e你因作弊被踢出了服务器 §i| §bWasteAC 反作弊检测
              §i请重新加入服务器.....
  # 默认变量
  # %year% - 封禁的年
  # %month% - 封禁的月
  # %day% - 封禁的日
  # %hour% - 封禁的时
  # %minute% - 封禁的分
  # %second% - 封禁的秒
  # %id% - 封禁ID
  # %player% - 作弊玩家
  # %type% - 作弊类型
  banned_message: |-
    §r§r
                    §l§c>> BANNED MESSAGE <<
             §i连接已丢失,你因作弊被服务器封禁了
    §e时间: %year% 年 %month% 月 %day% 日 %hour% 时 %minute% 分 %second% 秒 §i| §bWasteAC 反作弊检测
               §i申诉解封和疑问QQ群: §f12345678
  # 默认变量
  # %player% - 作弊玩家
  # %type% - 作弊类型
  broadcast_message: "§l[§bWasteAC§f] §c一名玩家因作弊或滥用游戏漏洞被踢出了服务器 §b感谢你的举报,为游戏创造更好的环境!"
